### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by HenrikStaaf** [KaTeX/KaTeX#2197] opened 2020-02-07 09:33 UTC
Are different fonts for Katex supported? Right now it's only one font we can use right?

**Comment by ronkok** [comment] 2020-02-08 18:25
> Right now it's only one font we can use right?

Correct. KaTeX code is closely linked to the font metrics of the KaTeX font. Any other font will result in incorrect character mapping and vertical mis-alignments.

**Comment by edemaine** [comment] 2020-02-20 14:36
Closing as duplicate of #123.

**Closed by edemaine** 2020-02-20 14:36 UTC
Labels: enhancement
