### ISSUE TITLE
Add command \iddots

### ISSUE THREAD

**Issue by lcswillems** [KaTeX/KaTeX#2734] opened 2021-01-15 08:28 UTC
**Is your feature request related to a problem? Please describe.**
Hi, KaTeX already includes the `\ddots` command. However, it is missing its cousin, the `\iddots` that displays `⋰` [3 dots in the anti-diagonal](https://tex.stackexchange.com/a/32218).

**Comment by ylemkimon** [comment] 2021-04-05 18:29
Duplicate of #1223.

**Comment by ylemkimon** [comment] 2021-04-05 18:30
Duplicate of #1223

**Closed by ylemkimon** 2021-04-05 18:29 UTC
Labels: enhancement
