### ISSUE TITLE
No character metrics for ' ' (non-breaking space) in style 'Main-Bold'

### ISSUE THREAD

**Issue by tommyip** [KaTeX/KaTeX#1994] opened 2019-06-05 07:22 UTC
Having a space in the input to `\textbf` triggers this warning, the rendered output looks fine though. It seems like KaTeX is converting the space into a non-breaking space.

**Comment by edemaine** [comment] 2019-06-05 18:40
@tommyip Thanks for the report. This is likely because the bold font fails to include a space character like the other fonts. (In all cases, space maps to nonbreaking space.) We should definitely fix this.

**Comment by ylemkimon** [comment] 2019-06-06 17:42
Duplicate of https://github.com/KaTeX/katex-fonts/issues/62

**Closed by ylemkimon** 2019-06-06 17:42 UTC
Labels: bug, fonts

**Comment by timabbott** [comment] 2019-07-03 23:53
I just wanted to post a simple reproducer, since apparently display mode is required:
```
$ node ./node_modules/katex/cli.js -d
\pi \textbf{ is not } 3.14
No character metrics for ' ' in style 'Main-Bold'
No character metrics for ' ' in style 'Main-Bold'
No character metrics for ' ' in style 'Main-Bold'
<span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>π</mi><mrow><mtext> </mtext><mtext mathvariant="bold">is</mtext><mtext> </mtext><mtext mathvariant="bold">not</mtext><mtext> </mtext></mrow><mn>3.14</mn></mrow><annotation encoding="application/x-tex">\pi \textbf{ is not } 3.14
</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.69444em;vertical-align:0em;"></span><span class="mord mathdefault" style="margin-right:0.03588em;">π</span><span class="mord text"><span class="mord textbf"> is not </span></span><span class="mord">3</span><span class="mord">.</span><span class="mord">1</span><span class="mord">4</span></span></span></span></span>
```

We care about this in Zulip mainly because it's the only spam output in out frontend unit test suite, so not super important, but would be nice to get fixed.

p.s. howdy @edemaine! :)
