### ISSUE TITLE
ParseError: KaTeX parse error: \tag works only in display equations

### ISSUE THREAD

**Issue by zgpnuaa** [KaTeX/KaTeX#2277] opened 2020-06-20 08:15 UTC
I use \tag{1} to add formula number, but there is a error "ParseError: KaTeX parse error: \tag works only in display equations".

**Comment by edemaine** [comment] 2020-06-20 12:26
This is how LaTeX works, and intended behavior: you need to use display math (e.g. `$$...$$`) so that there's a right margin to put the tag in. Perhaps there's more to your context that you could explain?

**Comment by edemaine** [comment] 2020-07-09 12:40
Closing for now. Let us know if you need further help.

**Closed by edemaine** 2020-07-09 12:40 UTC
Labels: bug

**Comment by fedemolina** [comment] 2022-07-13 03:52
Same problem occurs when using jupyter notebook inside visual code using two tags in same math equations ($$.....$$)

Example:

$$\begin{align}
\frac{\partial J(w,b)}{\partial w}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f(x^{(i)}) - y^{(i)})x^{(i)} \tag{4}\\
  \frac{\partial J(w,b)}{\partial b}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f(x^{(i)}) - y^{(i)}) \tag{5}\\
\end{align}$$

**Comment by mbourne** [comment] 2022-07-13 04:22
Fedemolina

Your equation works fine (apart from the overlapping tags) with no errors in the KaTeX demo, and looks like this:

![image](https://user-images.githubusercontent.com/7541940/178649298-9c45f0b3-c61d-4ea0-9a12-5a7e4b30877a.png)

Did you mean to post your response in one of the overlapping tag threads?

For others trying to figure what's happening in your post, your equation (in double dollar signs) was actually rendered by MathJax above. I notice MathJax ignores your tag numbers. 

This is Fedemolina's equation:

\begin{align} \frac{\partial J(w,b)}{\partial w} &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f(x^{(i)}) - y^{(i)})x^{(i)} \tag{4}\\ \frac{\partial J(w,b)}{\partial b} &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f(x^{(i)}) - y^{(i)}) \tag{5}\\ \end{align}

**Comment by kylincodelab** [comment] 2023-09-22 15:50
it not work now

**Comment by kylincodelab** [comment] 2023-09-22 15:50
f*ck

**Comment by edemaine** [comment] 2023-09-22 17:15
@kylincodelab Please open a new issue if you're having a specific problem.
