### ISSUE TITLE
\neq 显示错误

### ISSUE THREAD

**Issue by lsa110** [KaTeX/KaTeX#1937] opened 2019-04-14 09:03 UTC
> Before reporting a bug
- [ ] Check [common issues](https://katex.org/docs/issues.html).
- [ ] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [ ] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
A clear and concise description of what the bug is. If your installation is available on the web or you can provide a minimal repo or CodePen that reproduces the bug, please add the link to it.

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Environment (please complete the following information):**
 - KaTeX Version: [Can be checked via `katex.version`]
 - Device: [e.g. Desktop, iPhone 8]
 - OS: [e.g. Windows 10, iOS 11]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 72]

**Additional context:**
Add any other context about the problem here. If you're using a library to use KaTeX, please include its name and setup.

**Comment by lsa110** [comment] 2019-04-14 09:04
\neq 显示错误

**Comment by kevinbarabash** [comment] 2019-04-17 03:50
[a \neq b](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22f(%231)%22%7D%2C%22code%22%3A%22a%5C%5Cneq%20b%22%7D) works on katex.org.  Can you provide more details about the issue you're having?

**Comment by voronin-ivan** [comment] 2019-04-19 09:37
+1
Can reproduce only in Safari (desktop and mobile)
![Screen Shot 2019-04-19 at 12 36 19](https://user-images.githubusercontent.com/13902831/56418520-cec74a00-629f-11e9-8609-f0df6411a58d.png)

**Comment by kevinbarabash** [comment] 2019-04-22 00:30
Closing as a duplicate of #1941.

**Closed by kevinbarabash** 2019-04-22 00:30 UTC
Labels: bug, more info needed
