### ISSUE TITLE
'Too many tab characters' for split equation with multiple '&' characters on a line

### ISSUE THREAD

**Issue by mjbvz** [KaTeX/KaTeX#3634] opened 2022-05-16 23:55 UTC
> Before reporting a bug
- [X] Check [common issues](https://katex.org/docs/issues.html).
- [X] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [X] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**To Reproduce:**
Try rendering the following equation:

```
\begin{split}
x &= y &= z
\end{split}
```

**Expected behavior:**
This should render as (tested with MathJax):
![Screen Shot 2022-05-16 at 4 52 21 PM](https://user-images.githubusercontent.com/12821956/168700451-f387ee5c-51ba-4ddb-8f7c-5ad4bd40fdeb.png)

**Actual Behavior**
I see the following error:

```
KaTeX parse error: Too many tab characters: & at position 22: …{split} x &= y &̲= z \end{split}
```

**Environment (please complete the following information):**
 - KaTeX Version: 0.15.3
 - Device: Desktop
 - OS: MacOS 
 - Browser: Safari 15.4
 - Version: [e.g. 72]

**Additional context:**
I've simplified the sample above. The full text of the original equation was:

```
\begin{equation}
\begin{split}
x &= 2 * 3 &= 6 \\
y &= 4 * 5 &= 20
\end{split}
\end{equation}
```

**Comment by ronkok** [comment] 2022-05-17 20:04
KaTeX does not emulate MathJax; it emulates LaTeX. You'll find that multiple alignment characters will result in an error in LaTeX. 

If you need multiple alignment characters and a single tag number, you might try something like:

```
\begin{alignat}{2}
x &= 2 * 3 &= 6 \\
\notag y &= 4 * 5 &= 20
\end{alignat}
```

[rendered example](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22%5C%5Cbegin%7Balignat%7D%7B2%7D%5Cnx%20%26%3D%202%20*%203%20%26%3D%206%20%5C%5C%5C%5C%5Cn%5C%5Cnotag%20y%20%26%3D%204%20*%205%20%26%3D%2020%5Cn%5C%5Cend%7Balignat%7D%22%7D)

**Comment by ronkok** [comment] 2022-05-20 03:08
It's not a bug. KaTeX is faithfully emulating LaTeX behaviour. So I am closing this issue.

**Closed by ronkok** 2022-05-20 03:08 UTC
Labels: bug
