### ISSUE TITLE
Vertical bar overlapping

### ISSUE THREAD

**Issue by 88250** [KaTeX/KaTeX#3669] opened 2022-07-09 04:07 UTC
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

Vertical line rendering overlaps:

![image](https://user-images.githubusercontent.com/873584/178090917-13073c26-57f7-45c3-9199-4d93450d5972.png)

**To Reproduce:**

```markdown
 \left|f(x)-\frac{A(x+h)-A(x)}{h}\right|
```

**Expected behavior:**

Rendering is aligned without overlapping.

**Screenshots:**

![image](https://user-images.githubusercontent.com/873584/178090972-2d45c65a-6ce4-4ffa-a81c-45af91eb4eed.png)

**Environment (please complete the following information):**
 - KaTeX Version: v0.16.0
 - Device: Desktop
 - OS: Windows 11
 - Browser: Chrome 103.0.5060.114
 - Version:

**Additional context:**

```js
{
    displayMode: true,
    output: "html",
}

**Comment by edemaine** [comment] 2022-07-09 04:19
I believe this is a duplicate of #3168. Unfortunately we do not know how to improve this situation. We should be giving the correct coordinates to the browser, but fonts and browsers are complicated, so subpixel differences are difficult to avoid.

**Closed** 2022-07-09 04:20 UTC
Labels: bug, duplicate

**Comment by 88250** [comment] 2022-07-09 04:44
@edemaine Thanks.
