### ISSUE TITLE
Display format not operative in custom element, poor/nonexistent display in some browsers

### ISSUE THREAD

**Issue by jxxcarlson** [KaTeX/KaTeX#2286] opened 2020-07-08 17:37 UTC
> Before reporting a bug
- [x ] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
In a functioning custom element,  `displayMode: true` does not result in display mode rendering.

**To Reproduce:**
1. Go to https://jxxcarlson.github.io/app/katex/index.html using Firefox
2. Look at last equation.  It should be in display mode, but is not.

**Expected behavior:**
As noted above. But:
1. Second formula should be in display mode (Firefox)
2. Poor display in Safari (second equation, superscript)
3. No math display in Chrome

**Screenshots:**

<img width="295" alt="Screen Shot 2020-07-08 at 7 24 18 PM" src="https://user-images.githubusercontent.com/679991/86950819-f4fd3200-c150-11ea-8ab4-1f2a9178c7c9.png">
<img width="295" alt="Screen Shot 2020-07-08 at 7 25 10 PM" src="https://user-images.githubusercontent.com/679991/86950843-fe869a00-c150-11ea-95e4-2334df6b9eb2.png">
<img width="299" alt="Screen Shot 2020-07-08 at 7 24 33 PM" src="https://user-images.githubusercontent.com/679991/86950863-05ada800-c151-11ea-9ffc-f5b8ae9b35d3.png">

**Environment (please complete the following information):**
 - KaTeX Version: [Latest, first used today, July 8, 2020]
 - Device: [Desktop]
 - OS: [MacOS 10.14.6]
 - Browser: [Firefox, Safari, Chrome]
 - Version: [e.g. 77.0.1 ; 13.1.1 (14609.2.9.1.3); 83.0.4103.106]

**Additional context:**
I am using KaTeX in an Elm app: See https://github.com/jxxcarlson/meenylatex and also https://minilatex.io
See the katex branch, https://github.com/jxxcarlson/meenylatex/blob/katex/example/index-katex.html
Am evaluating KaTeX for use in my LaTeX > Html compiler. (Contact: jxxcarlson at gmail)
I use MathJax and KaTeX via custom elements.  For KaTeX, it is https://github.com/jxxcarlson/meenylatex/blob/katex/example/assets/elm-katex.js

For convenience, here is the code for elm-katex.js:

```

const init =  async function(app) {

  console.log("I am starting elm-katex: init");
  var katexJs = document.createElement('script')
  katexJs.type = 'text/javascript'
  katexJs.onload = initKatex
  katexJs.src = "https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js"

  document.head.appendChild(katexJs);
  console.log("elm-katex: I have appended katexJs to document.head");

}


function initKatex() {

  console.log("elm-katex: initializing");

  class MathText extends HTMLElement {

     constructor() {
         // Always call super first in constructor
         super();
       }

    connectedCallback() {
      console.log('katex connectedCallback',this.content )
      console.log('katex format',this.format )
      const displayMode = (this.format == 'display') ? true : false ;
      console.log ('displayMode', displayMode)

      this.attachShadow({mode: "open"});
      this.shadowRoot.innerHTML =
        katex.renderToString(
          this.content,
          { throwOnError: false, output: "mathml", displayMode: displayMode }
        );
    }

  }

  customElements.define('math-text', MathText)

}
```

**Comment by edemaine** [comment] 2020-07-08 17:58
I believe this is an issue with MathML, not KaTeX. (But @ronkok can correct me on that.) If you take out the `format: 'mathml'`, and let KaTeX do its thing (use both HTML and MathML output), you'll probably get better results.

**Comment by ronkok** [comment] 2020-07-08 18:25
This is a duplicate of #2219, which was fixed by PR #2220 in March. The problem is that we have not had a release issued since September. There are also some bug fix PRs waiting for review, much less release.

**Comment by edemaine** [comment] 2020-07-08 19:03
Thanks @ronkok. Agreed, and moving this discussion to #2287.

**Closed by edemaine** 2020-07-08 19:03 UTC
Labels: bug

**Comment by jxxcarlson** [comment] 2020-07-08 20:02
re the below, unfortunately not the case.  If I remove `output: mathml` from options in `elm-katex.js`, the output is as in the attached image.

> I believe this is an issue with MathML, not KaTeX. (But @ronkok can correct me on that.) If you take out the output: 'mathml', and let KaTeX do its thing (use both HTML and MathML output), you'll probably get better results.

<img width="373" alt="Screen Shot 2020-07-08 at 9 57 26 PM" src="https://user-images.githubusercontent.com/679991/86964510-790de480-c166-11ea-9152-5b0b40b494c5.png">

**Comment by ronkok** [comment] 2020-07-08 20:26
@jxxcarlson That's a cool looking project.

Re: Problems: let's take one thing at a time.  I went to the site at https://jxxcarlson.github.io/app/katex/index.html (Thanks for the link!) and added an attribute to the math element. That attribute being: `display: block`. The screenshot below shows the result in Firefox:
![MathDisplay](https://user-images.githubusercontent.com/16403058/86966497-20b2f480-c11e-11ea-8772-ed673a25f335.PNG)

That image looks pretty good to me, and PR#2220 sets that attribute correctly.  @edemaine is stepping up to do a release with that PR, so it should be available in the not-too-distant future.

Your second screenshot, omitting `output: mathml`, has me baffled. Do you have a link for it that I can visit?

**Comment by edemaine** [comment] 2020-07-08 20:54
That ugly rendering looks like you're missing the `katex.css` style file. If you add that in a `<style>` tag, the HTML rendering should work.

**Comment by jxxcarlson** [comment] 2020-07-22 05:49
Thanks so much @edemaine and @ronkok -- I will take a look at this again shortly in light of your comments above. Anxious to see how KaTeX works out with this project.

**Comment by jxxcarlson** [comment] 2020-07-23 05:46
I've got KaTeX working in an app at https://minilatex.lamdera.app/g/33 .  Followed your suggestions above (thanks!). Works perfectly in Firefox but not in other browsers, e.g. Chrome, Safari.

**Comment by ronkok** [comment] 2020-07-23 20:27
It works for me in Firefox, Chrome, and Edge. Nice stuff.

**Comment by jxxcarlson** [comment] 2020-07-23 20:35
Oops, I think there is one more step, as seen in the image below.  Do I need to add some fonts or something?

<img width="528" alt="Screen Shot 2020-07-23 at 4 28 42 PM" src="https://user-images.githubusercontent.com/679991/88336146-7ed8fd80-cd02-11ea-92d6-c4d2dcd49f44.png">

**Comment by ronkok** [comment] 2020-07-23 21:11
Re: Fonts. KaTeX HTML does require reference to the KaTeX fonts. If you are self-hosting KaTeX, then KaTeX expects the KaTeX fonts to be located in a directory called `fonts` which is a sibling of the `katex.min.css` stylesheet. All of those files are available from the tar files and zip files on the KaTeX [releases](https://github.com/KaTeX/KaTeX/releases) page.
