### ISSUE TITLE
Addition of the Derivatives package

### ISSUE THREAD

**Issue by TimeTravelPenguin** [KaTeX/KaTeX#3184] opened 2021-08-23 10:24 UTC
I am a mathematics student who uses an application that uses KaTeX, and noticed that this package isn't currently present. 

I find it very tedious to continuously have to type: $\dfrac{\partial^2 f}{\partial y \partial x}$ to do a second-degree partial derivative, for example. By contrast: $\pdv{f}{y, x}$ does this exactly. 

Although this library can be self-implemented in many contexts by defining my own macros, this is not possible in applications such as Notion.

Source: https://ctan.org/pkg/derivative?lang=en

**Comment by visika** [comment] 2021-09-02 13:23
This might be a duplicate of #3038. I'm tempted to look how we could implement that ourselves. That should boil down to edit the \frac family of functions. I guess they are defined here: https://github.com/KaTeX/KaTeX/blob/a5222165ef4aa29d903558cdc93f0fce7fc01217/src/functions/genfrac.js#L243

**Comment by edemaine** [comment] 2021-09-02 15:24
@visika Thanks for spotting the duplicate.  I'll close this issue, and suggest further discussion in #3038.

I wouldn't recommend using any of the genfrac code.  Instead, I would recommend using the macro system; see `src/macros.js`.  You can return a sequence of tokens that calls `\frac` instead of redefining `\frac`.

**Closed by edemaine** 2021-09-02 15:24 UTC
Labels: enhancement
