### ISSUE TITLE
\not (and \neq) broken in ~~Chrome 72~~ Safari

### ISSUE THREAD

**Issue by joergklein** [KaTeX/KaTeX#1842] opened 2019-02-04 08:21 UTC
$`\neq`$ or $`\not =`$ doesn't work correctly. Please take a look into the documentation too.

**Comment by edemaine** [comment] 2019-02-04 14:46
@joergklein What environment are you using KaTeX in?  The ``` $` ... `$ ``` notation looks like [Gitlab](https://docs.gitlab.com/ee/user/markdown.html#math).  Perhaps you should be asking your question in a Gitlab forum.

Does any math expression work for you? I'm guessing not, and that it's something about your configuration.

`\neq` and `\not=` are definitely supported by KaTeX; see [the demo page](https://katex.org/?data=%7B%22code%22%3A%22%5C%5Cneq%20%5C%5Cnot%3D%22%7D). They are also documented in the [list of supported features](https://katex.org/docs/supported.html).

**Comment by joergklein** [comment] 2019-02-04 16:11
Yes it is Gitlab. When I type on the demo page \neq then I see / =.
When I type \not= then I see also / =.
You wrote \neq \not= . Please take a look at the screen shot
![screenshot](https://user-images.githubusercontent.com/38553171/52220668-b7cbab00-289f-11e9-8e47-fc29e1b6a030.png)

**Comment by edemaine** [comment] 2019-02-04 16:42
@joelburget What web browser are you using? Safari perhaps?

Here's what I see on Chrome on Windows:

![image](https://user-images.githubusercontent.com/2218736/52222605-e763be80-2871-11e9-8f17-9cbf6f73b533.png)

**Comment by joergklein** [comment] 2019-02-04 18:32
The Browser is Chrome on CentOS 7. Firefox shows the correct sign on CentOS 7

**Comment by edemaine** [comment] 2019-02-04 18:33
What version of Chrome? I'm using 71.0.3578.98.

**Comment by q234rty** [comment] 2019-02-07 03:37
Having the same issue with Chrome 72.0.3626.96 on Windows.

**Comment by edemaine** [comment] 2019-02-07 23:03
OK, I updated to Chrome 72, and that seems to be the issue.  I can now reproduce the problem.  Chrome must have changed how it works with accents. ☹️

**Comment by edemaine** [comment] 2019-02-07 23:20
I believe there's a problem with the `\not` character in the font that we need to fix.  I find this view (from opentype.js.org) confusing, but in particular the `advanceWidth` of 1289 seems way too big:

![image](https://user-images.githubusercontent.com/2218736/52449328-e1d1d700-2b04-11e9-9e75-c2d2d8a2ae79.png)

@kevinbarabash Do you remember any outstanding issues here, e.g., plans to regularize this character? I think we already switched away from combining characters (https://github.com/KaTeX/katex-fonts/issues/3 lists some other accents where this still needs to happen).

**Comment by matteo-ronchetti** [comment] 2019-02-09 15:51
Got the same problem in Chrome 72, as a workaround I replaced "\not =" with "=\not\," and it shows the symbol correctly ([see demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22f(%231)%22%7D%2C%22code%22%3A%22%3D%5C%5Cnot%5C%5C%2C%22%7D)).

**Comment by edemaine** [comment] 2019-02-09 18:58
Actually, I think the glyph is fine -- it has no negative leading space.  My current theory is that, because we use U+0338 for the glyph, which is a combining character (which we did because there is no non-combining LONG SOLIDUS Unicode slot), Chrome forces it to the left.  Why Chrome 72 changed this, I'm not sure (nor have I found documentation).  I'll have to try mapping it to a different slot, and see if that fixes the problem...

**Comment by edemaine** [comment] 2019-02-09 19:56
https://github.com/KaTeX/katex-fonts/pull/58 is (most of) a fix to this bug.

**Comment by kevinbarabash** [comment] 2019-02-09 21:58
This is ridiculous.  First Safari can't handle negative advance so we get rid of it and then Chrome decides to add negative advance to combining characters that don't have it. 😞 

@edemaine thanks for coming up with a fix for this. 🙂

**Comment by infusion** [comment] 2019-02-17 14:28
Can confirm this problem with `\neq` on OSX and newest Chrome 72.0.3626.109

**Comment by robbienohra** [comment] 2019-02-18 17:14
I'm having the same issue with Chrome 72.0.3626.109
Freakin' hell.

**Comment by edemaine** [comment] 2019-02-18 17:33
@kevinbarabash Could you review the fix in https://github.com/KaTeX/katex-fonts/pull/58?

**Comment by eneso** [comment] 2019-02-18 17:34
Same issue with Chrome 71.0.3578.98.

**Comment by edemaine** [comment] 2019-02-18 17:37
@eneso On which platform? Chrome 71 worked fine for me on Windows.

**Comment by eneso** [comment] 2019-02-18 17:41
> @eneso On which platform? Chrome 71 worked fine for me on Windows.

Actually as of today, it is appearing correctly. Yesterday I was having this issue but today it is displaying just fine. Thanks.

**Comment by robbienohra** [comment] 2019-02-19 14:18
Anything I can do to help speed up the fix? @edemaine  do you need to us to test your fix? I'm currently on GatsbyJS using this `css` dependency `require(`katex/dist/katex.min.css`)`

**Comment by edemaine** [comment] 2019-02-20 22:13
For those in a rush to deploy this fix (as I was) and using KaTeX via npm, you can use
```sh
npm install https://github.com/edemaine/KaTeX/tarball/fixnot-dist
```
to get a release with this bug fixed -- but also with potentially dangerous unprotected `\includegraphics` support, so beware!

**Comment by robbienohra** [comment] 2019-02-20 23:02
Thanks, dude!

**Comment by ylemkimon** [comment] 2019-02-22 09:27
v0.10.1 is released, which includes a hotfix to this bug!

**Comment by d00mw01f** [comment] 2019-02-27 13:15
After v0.10.1 release \neq broken in Safari:
![image](https://user-images.githubusercontent.com/3918106/53492791-4bbe1a80-3acc-11e9-8530-936ea1c462b1.png)

**Comment by edemaine** [comment] 2019-02-27 14:05
That's unfortunate... I unfortunately do not have easy access to Safari, so it would be nice to get confirmation, and some analysis as to what's going on. How does the `\not` accent differ from other accent characters?

**Comment by d00mw01f** [comment] 2019-02-28 13:25
Reproduced both on real mac in Safari and in browserstack.  
Also reproduced on iPhone in Safari, Chrome and Firefox (do they have same engine?)
I tried to investigate the problem and managed to find that Safari doesn't render `@not` symbol (`\ue020`). But it will render it if symbol has border. Hope this will help.

**Comment by ylemkimon** [comment] 2019-02-28 13:49
> [D]o they have same engine?

Non-Safari uses the same engine, WebKit.

**Comment by congxinUSC** [comment] 2019-03-16 22:14
Am I the only one seeing a not filled square after the update on Chrome 72 & Safari?

**Closed** 2019-03-21 05:50 UTC
Labels: bug, high priority

**Comment by jhugon61** [comment] 2019-04-21 13:03
FWIW, a colleague suggested a workaround which appears to work on Safari with 0.10.1: use \cancel= instead of \neq. Granted the display is different for these two commands, but maybe others will find this is a useful workaround until the issue is fixed.

**Comment by nrailgun** [comment] 2019-05-06 09:46
same issue on firefox 66.

**Comment by kevinbarabash** [comment] 2019-05-13 03:08
I've published 0.10.2 with a fix for this on Safari.
<img width="1392" alt="Screen Shot 2019-05-12 at 11 07 25 PM" src="https://user-images.githubusercontent.com/1044413/57593755-e1cde280-750a-11e9-9b4a-7eedb27116bc.png">

**Comment by jhugon61** [comment] 2019-05-13 06:00
Thank you very much, Kevin.
~~~~~~~~~~~~~~~~~~~~~
Jacques Hugon
jacques.hugon@gmail.com
~~~~~~~~~~~~~~~~~~~~~

**Comment by kevinbarabash** [comment] 2019-05-13 13:23
@jhugon61 it was @ylemkimon who actually fixed the issue.  I just did the publish.
