### ISSUE TITLE
Math inside HTML table breaks

### ISSUE THREAD

**Issue by sapphire008** [KaTeX/KaTeX#2141] opened 2019-10-29 20:28 UTC
KaTex cannot render equations when they are inside an html table
```
<table>
    <tr>
        <td>$p_1$</td>
    </tr>
</table>
```

Although it can render inside a `<span>` (perhaps only `<span>`; `<div>` also does not allow rendering)

`<span>$p_1$<span>`

Tested in Atom's Markdown Preview Enhanced as a test (which allows both KaTex and MathJax modes; KaTex does not render while MathJax renders correctly) and Joplin (uses only KaTex; does not render)

**Comment by edemaine** [comment] 2019-10-29 20:50
I believe this is a duplicate of #2100, which is solved on master branch via PR #2103 but not yet in a release (perhaps should be). You can fix it temporarily by adding a border-collapse rule as in #2103.

**Closed by edemaine** 2019-10-29 20:50 UTC
Labels: bug
