### ISSUE TITLE
Line spacing with bare \\ in display math

### ISSUE THREAD

**Issue by xiewl** [KaTeX/KaTeX#1991] opened 2019-05-30 06:50 UTC
This is Code
`$$ \dfrac 25  + \dfrac 24 \\ \dfrac 21 + \dfrac 26 $$`
`$$ \begin{aligned} &\dfrac 25  + \dfrac 24 \\ &\dfrac 21 + \dfrac 26 \end{aligned} $$`

screenshot with katex：
<img width="140" alt="WX20190530-144859@2x" src="https://user-images.githubusercontent.com/15881722/58614119-194dd480-82ea-11e9-9a24-04fd760a5338.png">

screenshot with mathjax：
<img width="237" alt="WX20190530-145000@2x" src="https://user-images.githubusercontent.com/15881722/58614167-3b475700-82ea-11e9-882a-17fdbe98a69b.png">

**Comment by kevinbarabash** [comment] 2019-07-09 03:02
By default we match LaTeX's rendering which looks like:
<img width="162" alt="Screen Shot 2019-07-08 at 11 00 28 PM" src="https://user-images.githubusercontent.com/1044413/60856164-3cff1700-a1d4-11e9-8afc-dcd9a0730edd.png">

The spacing can be adjusted by putting using `// [0.5em]` instead of `//`.  For more discussion see #312.  We're planning on adding `\setlength` which should make fixing spacing issues like these easier.  I'm going to close this as a duplicate of #312.

**Closed by kevinbarabash** 2019-07-09 03:02 UTC
Labels: bug
