### ISSUE TITLE
`\vert` (or ASCII pipe) has an issue with `\Big`

### ISSUE THREAD

**Issue by neilbalch** [KaTeX/KaTeX#3400] opened 2021-11-06 06:27 UTC
**Describe the bug:**
When the `\vert` or raw pipe character is used with `\big`, e.g. in the following sample, the pipe character is rendered in a way that sometimes results in a noticeable vertical break between a distinct top and bottom section.

**To Reproduce:**
Try to render the following, for example in the example renderer on [https://katex.org](https://katex.org/):

```latex
E_z = k\lambda z \int_{-a}^b \frac{dx}{(z^2 + x^2)^{3/2}}
= \frac{k\lambda}{z}\left(\frac{x}{\sqrt{z^2 + x^2}}\right)\Big|_{-a}^b
= \frac{k\lambda}{z}\left(\frac{b}{\sqrt{z^2 + b^2}} + \frac{a}{\sqrt{z^2 + a^2}}\right)
```

**Expected behavior:**
The vertical pipe should be composed of a single line or pipe character stretched/duplicated exactly on top of one another.

**Screenshots:**
![From katex.org](https://user-images.githubusercontent.com/3847882/140600151-5987f5d5-8bdb-4f28-a118-f678613376cf.png)
![closeup from previous image](https://user-images.githubusercontent.com/3847882/140600155-1bdd3454-665e-4dc2-ae48-78bedc811a9b.png)
More obvious example rendered in [Notion](notion.so):
![more obvious example rendered in Notion](https://user-images.githubusercontent.com/3847882/140600183-76b0ecbe-a4cb-41d1-a05c-2f94bf4010de.png)

**Environment (please complete the following information):**
 - KaTeX Version: Unknown, using Notion embedded version and katex.org website
 - Device: Desktop and Android - OS: Windows 10
 - Browser: Firefox and Notion/ElectronJS

**Comment by edemaine** [comment] 2021-11-08 15:37
Duplicate of #3168, so we should continue discussion there. But we changed some things to improve this recently, so it's good to know that this remains an issue.

I personally can't reproduce it (on katex.org), on my high-DPI displays. I imagine it mostly happens on low/regular-DPI displays.

**Closed by edemaine** 2021-11-08 15:37 UTC
Labels: bug

**Comment by neilbalch** [comment] 2021-11-08 18:17
> 
> 
> Duplicate of #3168, so we should continue discussion there. But we changed some things to improve this recently, so it's good to know that this remains an issue.
> 
> I personally can't reproduce it (on katex.org, on Chrome or Firefox, on Windows 10), on my high-DPI displays. I imagine it mostly happens on low/regular-DPI displays.

Interesting... Understood, sorry for making a dupe issue
