### ISSUE TITLE
Katex \tag is overlapped when a formula is too long

### ISSUE THREAD

**Issue by langtutheky** [KaTeX/KaTeX#2322] opened 2020-07-17 18:24 UTC
## Description

Adding a \tag to a formula, the \tag would overlap the formula when rendered if the formula is too long

## To reproduce

1. Type a very long formula into the [Katex's Checker](https://katex.org/)
2. Insert a \tag at the end of the formula
3. See the error

## Expected behaviors

No matter how long the formula is, the \tag should always be at the tail of the formula and not overlapping it

## Environments

 - Katex Version: 0.12.0
 - Device: Desktop
 - OS: MacOS Catalina 
 - OS Version: 10.15.5
 - Browser: Google Chrome
 - Broswer Version: 83.0.4103.116

## Screenshots

```Tex
\[\forall v \forall w \forall x \forall y \forall z [[Bar(z) \wedge Foo(y) \wedge [\neg Baz(y)] \wedge Bar(x, y) \wedge Foo(w, y, z) \wedge Bar(v, w)] \rightarrow v = x] \forall v \forall w \forall x \forall y \forall z [[Bar(z) \wedge Foo(y) \wedge [\neg Baz(y)] \wedge Bar(x, y) \wedge Foo(w, y, z) \wedge Bar(v, w)] \rightarrow v = x] \tag{99} \]
```
<img width="853" alt="Screen Shot 2020-07-17 at 11 20 54 AM" src="https://user-images.githubusercontent.com/9475206/87818561-9d7d5700-c81f-11ea-916c-4cfde21c465e.png">

## Note

This is a redirected issue from the original issue that I posted on [Markdown Preview Enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/389)

**Comment by ylemkimon** [comment] 2020-07-17 18:33
Thank you for the report! This issue is a duplicate of #1983. So I'll close the issue. Feel free to reopen or open a new issue if you have different issues.

**Closed by ylemkimon** 2020-07-17 18:33 UTC
Labels: bug
