### ISSUE TITLE
Default delimiters _very_ hard to find!

### ISSUE THREAD

**Issue by jameshfisher** [KaTeX/KaTeX#1978] opened 2019-05-18 19:21 UTC
To find how to use the auto-render extension, I had to read through the source itself to find this: https://github.com/KaTeX/KaTeX/blob/master/contrib/auto-render/auto-render.js#L96-L107

Where are the examples or docs?

**Comment by ronkok** [comment] 2019-05-18 21:15
This is a duplicate of issue #1944, so I'm closing this issue. @jameshfisher, if it makes you feel better, I've just submitted a PR which should resolve the issue.

**Closed by ronkok** 2019-05-18 21:15 UTC

**Comment by ronkok** [comment] 2019-05-19 15:54
This issue is resolved by PR #1979. After the next KaTeX update, the documentation at https://katex.org/docs/autorender.html will be complete. Until then, the complete version is visible at https://katex.org/docs/next/autorender.html.
